In [1]:
my_list = [1, 2, 3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros([5, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones([3, 5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.random.rand(5)

array([0.10360101, 0.35292963, 0.29014093, 0.63954887, 0.66877156])

In [17]:
np.random.rand(5, 5)

array([[0.93983681, 0.14184049, 0.06223878, 0.72241836, 0.78153741],
       [0.29200091, 0.32339792, 0.08233024, 0.85266235, 0.75540138],
       [0.88960464, 0.69012475, 0.04261707, 0.31435698, 0.06589729],
       [0.42083995, 0.00104403, 0.59088245, 0.3698119 , 0.01597979],
       [0.24665386, 0.03660763, 0.98603856, 0.69788715, 0.27579771]])

In [18]:
np.random.randn(3)

array([-0.02903837,  0.30765446,  0.64650139])

In [20]:
np.random.randint(1, 100, 10)

array([13, 65, 51, 42, 37, 51, 28, 73, 21, 19])

In [21]:
arr = np.arange(25)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
ranarr = np.random.randint(0, 50, 10)

In [24]:
ranarr

array([ 3, 30,  5,  6, 12, 31, 48, 42, 44, 12])

In [25]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
ranarr.max()

48

In [27]:
ranarr.argmax()

6

In [28]:
arr1 = arr.reshape(5, 5)

In [29]:
arr1.shape

(5, 5)

In [30]:
arr1.dtype

dtype('int32')